services:
  # A Docker web service for Dagit
  - type: web
    name: dagit
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./dagit/Dockerfile
    dockerContext: ./dagit
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    healthCheckPath: /dagit_info
    envVars:
      - key: DAGSTER_PG_USERNAME
        fromDatabase:
          name: dagster_db
          property: user
      - key: DAGSTER_PG_PASSWORD
        fromDatabase:
          name: dagster_db
          property: password
      - key: DAGSTER_PG_HOST
        fromDatabase:
          name: dagster_db
          property: host
      - key: DAGSTER_PG_PORT
        fromDatabase:
          name: dagster_db
          property: port
      - key: DAGSTER_PG_DB
        fromDatabase:
          name: dagster_db
          property: database

  - type: pserv
    name: team_a_repository_grpc
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./team_a_repository/Dockerfile
    dockerContext: ./team_a_repository
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    envVars:
      - key: DAGSTER_PG_USERNAME
        fromDatabase:
          name: dagster_db
          property: user
      - key: DAGSTER_PG_PASSWORD
        fromDatabase:
          name: dagster_db
          property: password
      - key: DAGSTER_PG_HOST
        fromDatabase:
          name: dagster_db
          property: host
      - key: DAGSTER_PG_PORT
        fromDatabase:
          name: dagster_db
          property: port
      - key: DAGSTER_PG_DB
        fromDatabase:
          name: dagster_db
          property: database

  - type: pserv
    name: team_b_repository_grpc
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./team_b_repository/Dockerfile
    dockerContext: ./team_b_repository
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    envVars:
      - key: DAGSTER_PG_USERNAME
        fromDatabase:
          name: dagster_db
          property: user
      - key: DAGSTER_PG_PASSWORD
        fromDatabase:
          name: dagster_db
          property: password
      - key: DAGSTER_PG_HOST
        fromDatabase:
          name: dagster_db
          property: host
      - key: DAGSTER_PG_PORT
        fromDatabase:
          name: dagster_db
          property: port
      - key: DAGSTER_PG_DB
        fromDatabase:
          name: dagster_db
          property: database

databases:
  - name: dagster_db
    region: frankfurt
    plan: standard
    ipAllowList: [] # only allow internal connections
