services:
  # A Docker web service for Dagit
  - type: web
    name: dagit
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./Dockerfile
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    healthCheckPath: /dagit_info
    envVars:
      - key: GRPC_HOST
        fromService:
          name: grpc
          type: pserv
          property: host # available properties are listed below
      - key: GRPC_PORT
        fromService:
          name: grpc
          type: pserv
          property: port

  - type: pserv
    name: grpc
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./Dockerfile
    dockerCommand: ./grpc_entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    healthCheckPath: /dagit_info
