services:
  # A Docker web service for Dagit
  - type: web
    name: dagit
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./dagit/Dockerfile
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
    healthCheckPath: /dagit_info

  - type: pserv
    name: team_a_repository_grpc
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./team_a_repository/Dockerfile
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master

  - type: pserv
    name: team_b_repository_grpc
    env: docker
    repo: https://github.com/helloworld/dagster-demo # optional
    dockerfilePath: ./team_b_repository/Dockerfile
    dockerCommand: ./entrypoint.sh
    region: oregon
    plan: standard
    branch: master
